In this lab, I used the skills acquired in the module and address the issues of handling missing data, correct the data type of the dataframe attribute and execute the processes of data standardization and data normalization on specific attributes of the dataset.

<h2>Table of Contents</h2>

<div class="alert alert-block alert-info" style="margin-top: 20px">
<ul>
    <li><a href="#Identify-and-handle-missing-values">Identify and handle missing values</a>
        <ul>
            <li><a href="#Identify-missing-values">Identify missing values</a></li>
            <li><a href="#Deal-with-missing-data">Deal with missing values</a></li>
            <li><a href="#Correct-data-format">Correct data format</a></li>
        </ul>
    </li>
    <li><a href="#Data-Standardization">Data standardization</a></li>
    <li><a href="#Data-Normalization">Data normalization (centering/scaling)</a></li>
    <li><a href="#Binning">Binning</a></li>
    <li><a href="#Indicator-Variable">Indicator variable</a></li>
</ul>
    
</div>
 
<hr>


Data wrangling is used to convert data from an initial format to a format that may be better for analysis.

<h3>Import data</h3>
<p>
You can find the "Automobile Dataset" from the following link: <a href="https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data">https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data</a>. 
</p>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from pyodide.http import pyfetch


from pyodide.http import pyfetch

async def download(url, filename):
    response = await pyfetch(url)
    if response.status == 200:
        with open(filename, "wb") as f:
            f.write(await response.bytes())
    else:
        raise Exception(f"Download failed with status {response.status}")
        
file_path="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-SkillsNetwork/labs/Data%20files/auto.csv"
file_name = "usedcars.csv"

await download(file_path, file_name)

### Load data into a dataframe adding headers

In [4]:
headers = ["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style",
         "drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type",
         "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
         "peak-rpm","city-mpg","highway-mpg","price"]

In [5]:
df = pd.read_csv(file_name, names = headers)

In [6]:

#Optionally for running locally
#filepath = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-SkillsNetwork/labs/Data%20files/auto.csv"
#df = pd.read_csv(filepath, header=None, names=headers)    # Utilize the same header list defined above

 Use the method <b>head(n)</b> to display n rows of the dataframe. 5 is default when argument not given.

In [7]:
# To see what the data set looks like, we'll use the head() method.
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

So, how do we identify all those missing values and deal with them?
How to work with missing data?

Steps for working with missing data:

1. Identify missing data
2. Deal with missing data
3. Correct data format

# Identify and handle missing values


### Identify missing values
<h4>Convert "?" to NaN</h4>
In the car data set, missing data comes with the question mark "?".
We replace "?" with NaN (Not a Number), Python's default missing value marker for reasons of computational speed and convenience. Use the function: 
 <pre>.replace(A, B, inplace = True) </pre>
to replace A by B.
inplace=True ensures that the change is made in the current dataframeand not made as a newcopy.

In [8]:
import numpy as np


print(df.isna().sum())
df.replace("?", np.nan, inplace = True)
# Check if any entries are missing values
print(df.isna().sum())
df.head(5)

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64
symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

### Evaluating for Missing Data

<mh4>Evaluating for Missing Data</h4>

The missing values are converted by default. Use the following functions to identify these missing values. You can use two methods to detect missing data:
<ol>
    <li><b>.isnull()</b></li>
    <li><b>.notnull()</b></li>
</ol>
The output is a boolean value indicating whether the value that is passed into the argument is in fact missing data.

In [9]:
missing_data = df.isnull()
missing_data.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

### Count missing values in each column
Using a for loop in Python, you can quickly figure out the number of missing values in each column. As mentioned above, "True" represents a missing value and "False" means the value is present in the data set. In the body of the for loop the method ".value_counts()" counts the number of "True" values.

In [10]:
for column in missing_data.columns.values.tolist():
    #print(column)
    data = missing_data[column].value_counts()
    print(type(data))
    print(missing_data[column].value_counts())
    print("")

<class 'pandas.Series'>
symboling
False    205
Name: count, dtype: int64

<class 'pandas.Series'>
normalized-losses
False    164
True      41
Name: count, dtype: int64

<class 'pandas.Series'>
make
False    205
Name: count, dtype: int64

<class 'pandas.Series'>
fuel-type
False    205
Name: count, dtype: int64

<class 'pandas.Series'>
aspiration
False    205
Name: count, dtype: int64

<class 'pandas.Series'>
num-of-doors
False    203
True       2
Name: count, dtype: int64

<class 'pandas.Series'>
body-style
False    205
Name: count, dtype: int64

<class 'pandas.Series'>
drive-wheels
False    205
Name: count, dtype: int64

<class 'pandas.Series'>
engine-location
False    205
Name: count, dtype: int64

<class 'pandas.Series'>
wheel-base
False    205
Name: count, dtype: int64

<class 'pandas.Series'>
length
False    205
Name: count, dtype: int64

<class 'pandas.Series'>
width
False    205
Name: count, dtype: int64

<class 'pandas.Series'>
height
False    205
Name: count, dtype: int64

<class 'pandas.Series'>
curb-weight
False    205
Name: count, dtype: int64

<class 'pandas.Series'>
engine-type
False    205
Name: count, dtype: int64

<class 'pandas.Series'>
num-of-cylinders
False    205
Name: count, dtype: int64

<class 'pandas.Series'>
engine-size
False    205
Name: count, dtype: int64

<class 'pandas.Series'>
fuel-system
False    205
Name: count, dtype: int64

<class 'pandas.Series'>
bore
False    201
True       4
Name: count, dtype: int64

<class 'pandas.Series'>
stroke
False    201
True       4
Name: count, dtype: int64

<class 'pandas.Series'>
compression-ratio
False    205
Name: count, dtype: int64

<class 'pandas.Series'>
horsepower
False    203
True       2
Name: count, dtype: int64

<class 'pandas.Series'>
peak-rpm
False    203
True       2
Name: count, dtype: int64

<class 'pandas.Series'>
city-mpg
False    205
Name: count, dtype: int64

<class 'pandas.Series'>
highway-mpg
False    205
Name: count, dtype: int64

<class 'pandas.Series'>
price
False    201
True       4
Name: count, dtype: int64

### Dealing with missing data
<b>How should I deal with missing data?</b>

<ol>
    <li>Drop data<br>
        a. Drop the whole row?<br>
        b. Drop the whole column?
    </li>
    <li>Replace data<br>
        a. Replace it by mean?<br>
        b. Replace it by frequency?<br>
        c. Replace it based on other functions?
    </li>
</ol>

You should only drop whole columns if most entries in the column are empty. In the data set, none of the columns are empty enough to drop entirely.
You have some freedom in choosing which method to replace data; however, some methods may seem more reasonable than others. Apply each method to different columns:

<b>Replace by mean:</b>
<ul>
    <li>"normalized-losses": 41 missing data, replace them with mean</li>
    <li>"stroke": 4 missing data, replace them with mean</li>
    <li>"bore": 4 missing data, replace them with mean</li>
    <li>"horsepower": 2 missing data, replace them with mean</li>
    <li>"peak-rpm": 2 missing data, replace them with mean</li>
</ul>

<b>Replace by frequency:</b>
<ul>
    <li>"num-of-doors": 2 missing data, replace them with "four". 
        <ul>
            <li>Reason: 84% sedans are four doors. Since four doors is most frequent, it is most likely to occur</li>
        </ul>
    </li>
</ul>

<b>Drop the whole row:</b>
<ul>
    <li>"price": 4 missing data, simply delete the whole row
        <ul>
            <li>Reason: You want to predict price. You cannot use any data entry without price data for prediction; therefore any row now without price data is not useful to me.</li>
        </ul>
    </li>
</ul>

<h4>Calculate the mean value for the "normalized-losses" column </h4>

In [11]:
avg_norm_loss = df["normalized-losses"].astype("float").mean(axis=0)
print("Average of normalized-losses:", avg_norm_loss)

Average of normalized-losses: 122.0

#### Replace "NaN" with mean value in the "normalised-losses column"

In [12]:
df["normalized-losses"] = df["normalized-losses"].replace(np.nan, avg_norm_loss)

In [13]:
print(df["normalized-losses"].head())

0    122.0
1    122.0
2    122.0
3      164
4      164
Name: normalized-losses, dtype: object

<h4>Calculate the mean value for the "bore" column </h4>

In [14]:
mean_bore = df["bore"].astype("float").mean(axis=0)

In [15]:
mean_bore_rounded = round(mean_bore, 2)

In [16]:
print(mean_bore_rounded)

3.33

<h4>Replace "NaN" with mean value in the "bore column"</h4>

In [17]:
df["bore"] = df["bore"].replace(np.nan, mean_bore_rounded)

In [18]:
print(df["bore"].isna().sum())

0

In [19]:
# Calculate the mean value for "stroke" column

In [20]:
avg_stroke = df["stroke"].astype("float").mean(axis=0)
print("Average of stroke:", avg_stroke)

Average of stroke: 3.255422885572139

In [21]:
# replace NaN by mean value in "stroke" column

In [22]:
df["stroke"] = df["stroke"].replace(np.nan, avg_stroke)

In [23]:
<h4>Calculate the mean value for the "horsepower" column</h4>

<class 'SyntaxError'>: invalid syntax (<ipython-input-23-0345801bfc23>, line 1)

In [ ]:
avg_horsepower = df['horsepower'].astype('float').mean(axis=0)
print("Average horsepower:", avg_horsepower)

<h4>Replace "NaN" with the mean value in the "horsepower" column</h4>

In [ ]:
df['horsepower'] = df['horsepower'].replace(np.nan, avg_horsepower)

<h4>Calculate the mean value for "peak-rpm" column</h4>

In [ ]:
avg_peakrpm = df['peak-rpm'].astype('float').mean(axis=0)
print("Average peak rpm:", avg_peakrpm)

<h4>Replace "NaN" with the mean value in the "peak-rpm" column</h4>

In [ ]:
df['peak-rpm'] = df['peak-rpm'].replace(np.nan, avg_peakrpm)

To see which values are present in a particular column, we can use the ".value_counts()" method:

In [ ]:
print(df['num-of-doors'].value_counts())

I can see that four doors is the most common type. We can also use the ".idxmax()" method to calculate the most common type automatically:

In [ ]:
print(df['num-of-doors'].value_counts().idxmax())

The replacement procedure is very similar to what you have seen previously:

In [ ]:
#replace the missing 'num-of-doors' values by the most frequent 
df["num-of-doors"] = df["num-of-doors"].replace(np.nan, "four")

Finally, drop all rows that do not have price data:

In [ ]:
# simply drop whole row with NaN in "price" column
df.dropna(subset=["price"], axis=0, inplace=True)

# reset index, because we dropped four rows
df.reset_index(drop=True, inplace=True)

<b>Good!</b> Now, I have a data set with no missing values.

### Correct data format
<b>I am almost there! Kudos to me!</b>
<p>The last step in data cleaning is checking and making sure that all data is in the correct format (int, float, text or other).</p>

In Pandas, use:
<p><b>.dtypes</b> to check the data type</p>
<p><b>.astype()</b> to change the data type</p>

<h4>Let's list the data types for each column</h4>

In [ ]:
df.dtypes

<p>As you can see above, some columns are not of the correct data type. Numerical variables should have type 'float' or 'int', and variables with strings such as categories should have type 'object'. For example, the numerical values 'bore' and 'stroke' describe the engines, so you should expect them to be of the type 'float' or 'int'; however, they are shown as type 'object'. You have to convert data types into a proper format for each column using the "astype()" method.</p>

<h4>Convert data types to proper format</h4>

In [ ]:
df[["bore", "stroke"]] = df[["bore", "stroke"]].astype("float")
df[["normalized-losses"]] = df[["normalized-losses"]].astype("int")
df[["price"]] = df[["price"]].astype("float")
df[["peak-rpm"]] = df[["peak-rpm"]].astype("float")

In [ ]:
type(df["peak-rpm"])

In [ ]:
type(df[["peak-rpm"]])

<h4>Let us list the columns after the conversion</h4>

In [ ]:
df.dtypes

<b>Wonderful!</b>

Now I finally obtained the cleansed data set with no missing values and with all data in its proper format...AWESOME😍.

## Data Standardization
<p>
You usually collect data from different agencies in different formats.
(Data standardization is also a term for a particular type of data normalization where you subtract the mean and divide by the standard deviation.)
</p>
    
<b>What is standardization?</b>
<p>Standardization is the process of transforming data into a common format, allowing the researcher to make the meaningful comparison.
</p>

<b>Example</b>
<p>Transform mpg to L/100km:</p>
<p>In your data set, the fuel consumption columns "city-mpg" and "highway-mpg" are represented by mpg (miles per gallon) unit. Assume you are developing an application in a country that accepts the fuel consumption with L/100km standard.</p>
<p>You will need to apply <b>data transformation</b> to transform mpg into L/100km.</p>

<p>Use this formula for unit conversion:<p>
L/100km = 235 / mpg
<p>You can do many mathematical operations directly using Pandas.</p>

In [ ]:
df['city-mpg'].head()

In [ ]:
# Convert mpg to L/100km by mathematical operation (255 divided by mpg)
df['city-L/100km'] = 235/df["city-mpg"]

# Check your transformed data
df.head()

<div class="alert alert-danger alertdanger" style="margin-top: 20px">
<h2> Question  #2: </h2>

<b>According to the example above, transform mpg to L/100km in the column of "highway-mpg" and change the name of column to "highway-L/100km".</b>
</div>

In [ ]:
df['highway-L/100km'] = 235/df["highway-mpg"]

# Rename the column from highway-mpg to highway-L/100km
df.rename(columns = {'highway-mpg' : 'highway-L/100km'}, inplace = True)

df.head()

## Data Normalization

<b>Why normalization?</b>
<p>Normalization is the process of transforming values of several variables into a similar range. Typical normalizations include 
<ol>
    <li>scaling the variable so the variable average is 0</li>
    <li>scaling the variable so the variance is 1</li> 
    <li>scaling the variable so the variable values range from 0 to 1</li>
</ol>
</p>

<b>Example</b>
<p>To demonstrate normalization, say you want to scale the columns "length", "width" and "height".</p>
<p><b>Target:</b> normalize those variables so their value ranges from 0 to 1</p>
<p><b>Approach:</b> replace the original value by (original value)/(maximum value)</p>

In [ ]:
df['length'] = df['length'] / df['length'].max()
df['width'] = df['width']/df['width'].max()

In [ ]:
df['height'] = df['height']/df['height'].max() 

# show the scaled columns
df[["length","width","height"]].head()

I've normalized "length", "width" and "height" to fall in the range of [0,1] cool isn't it🥳

## Binning
<b>Why binning?</b>
<p>
    Binning is a process of transforming continuous numerical variables into discrete categorical 'bins' for grouped analysis.
</p>

<b>Example: </b>
<p>In your data set, "horsepower" is a real valued variable ranging from 48 to 288 and it has 59 unique values. What if you only care about the price difference between cars with high horsepower, medium horsepower, and little horsepower (3 types)? You can rearrange them into three ‘bins' to simplify analysis.</p>

<p>Use the Pandas method 'cut' to segment the 'horsepower' column into 3 bins.</p>

<h3>Example of Binning Data In Pandas</h3>

 Convert data to correct format:

In [ ]:
df["horsepower"]= df["horsepower"].astype(int).copy()

Plot the histogram of horsepower to see the distribution of horsepower.

In [ ]:
%matplotlib inline

plt.hist(df["horsepower"])

# set x/y labels and plot title
plt.xlabel("horsepower")
plt.ylabel("count")
plt.title("horsepower bins")

<p>Find 3 bins of equal size bandwidth by using Numpy's <code>linspace(start_value, end_value, numbers_generated</code> function.</p>
<p>Since you want to include the minimum value of horsepower, set start_value = min(df["horsepower"]).</p>
<p>Since you want to include the maximum value of horsepower, set end_value = max(df["horsepower"]).</p>
<p>Since you are building 3 bins of equal length, you need 4 dividers, so numbers_generated = 4.</p>

Build a bin array with a minimum value to a maximum value by using the bandwidth calculated above. The values will determine when one bin ends and another begins.

In [ ]:
bins = np.linspace(min(df['horsepower']), max(df["horsepower"]), 4)

# Set group names
group_names = ["low", "medium", "high"]

# Apply the function cut to determine what each value of df['horsepower'] belongs to
df['horsepower-binned'] = pd.cut(df['horsepower'], bins, labels=group_names, include_lowest=True)
df[['horsepower', 'horsepower-binned']].head(10)

In [ ]:
# See the number of vehicles in each bin:
df["horsepower-binned"].value_counts()

Plot the distribution of each bin:

In [ ]:
%matplotlib inline

plt.bar(group_names, df["horsepower-binned"].value_counts().reindex(group_names))

# set x/y labels and plot title
plt.xlabel("horsepower")
plt.ylabel("count")
plt.title("horsepower bins")

<p>
    Look at the data frame above carefully. You will find that the last column provides the bins for "horsepower" based on 3 categories ("Low", "Medium" and "High"). 
</p>
<p>
    I've successfully narrowed down the intervals from 59 to 3!😯😯😯😯
    I am so amazing😊🫢🤨👌
</p>

<h3>Bins Visualization</h3>
Normally, we would use a histogram to visualize the distribution of bins we created above.

In [ ]:
%matplotlib inline

# draw histogram of attribute "horsepower" with bins = 3
plt.hist(df["horsepower"], bins=3)

# set x/y labels and plot title
plt.xlabel("horsepower")
plt.ylabel("count")
plt.title("horsepower bins")

The plot above shows the binning result for the attribute "horsepower".

## Indicator Variable
<b>What is an indicator variable?</b>
<p>
    An indicator variable (or dummy variable) is a numerical variable used to label categories. They are called 'dummies' because the numbers themselves don't have inherent meaning. 
</p>

<b>Why use indicator variables?</b>
<p>
    You use indicator variables so you can use categorical variables for regression analysis in the later modules.
</p>
<b>Example</b>
<p>
    The column "fuel-type" has two unique values: "gas" or "diesel". Regression doesn't understand words, only numbers. To use this attribute in regression analysis, you can convert "fuel-type" to indicator variables.
</p>

<p>
    Use the Panda method 'get_dummies' to assign numerical values to different categories of fuel type. 
</p>

In [ ]:
df.columns

Get the indicator variables and assign it to data frame "dummy_variable_1":

In [26]:
dummy_variable_1 = pd.get_dummies(df["fuel-type"], dtype=int)
dummy_variable_1.head()

   diesel  gas
0       0    1
1       0    1
2       0    1
3       0    1
4       0    1

In [27]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

Change the column names for clarity:

In [28]:
dummy_variable_1.rename(columns={'gas':'fuel-type-gas', 'diesel':'fuel-type-diesel'}, inplace=True)

In [29]:
dummy_variable_1.head()

   fuel-type-diesel  fuel-type-gas
0                 0              1
1                 0              1
2                 0              1
3                 0              1
4                 0              1

In the data frame, column 'fuel-type' now has values for 'gas' and 'diesel' as 0s and 1s.

In [30]:
# merge data frame "df" and "dummy_variable_1"
df = pd.concat([df, dummy_variable_1], axis=1)
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,fuel-type-diesel,fuel-type-gas
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,3.47,2.68,9.0,111,5000,21,27,13495,0,1
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,3.47,2.68,9.0,111,5000,21,27,16500,0,1
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,2.68,3.47,9.0,154,5000,19,26,16500,0,1
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,3.19,3.40,10.0,102,5500,24,30,13950,0,1
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,3.19,3.40,8.0,115,5500,18,22,17450,0,1

In [31]:
# drop original column "fuel-type" from "df"
df.drop("fuel-type", axis = 1, inplace=True)

In [32]:
df.head()

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,fuel-type-diesel,fuel-type-gas
0,3,122.0,alfa-romero,std,two,convertible,rwd,front,88.6,168.8,...,3.47,2.68,9.0,111,5000,21,27,13495,0,1
1,3,122.0,alfa-romero,std,two,convertible,rwd,front,88.6,168.8,...,3.47,2.68,9.0,111,5000,21,27,16500,0,1
2,1,122.0,alfa-romero,std,two,hatchback,rwd,front,94.5,171.2,...,2.68,3.47,9.0,154,5000,19,26,16500,0,1
3,2,164,audi,std,four,sedan,fwd,front,99.8,176.6,...,3.19,3.40,10.0,102,5500,24,30,13950,0,1
4,2,164,audi,std,four,sedan,4wd,front,99.4,176.6,...,3.19,3.40,8.0,115,5500,18,22,17450,0,1

In [34]:
dummy_variable_2 = pd.get_dummies(df["aspiration"], dtype=int)
dummy_variable_2.head()

   std  turbo
0    1      0
1    1      0
2    1      0
3    1      0
4    1      0

In [35]:
# merge data frame "df" and "dummy_variable_2"
df = pd.concat([df, dummy_variable_2], axis = 1)
df.head()

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,fuel-type-diesel,fuel-type-gas,std,turbo
0,3,122.0,alfa-romero,std,two,convertible,rwd,front,88.6,168.8,...,9.0,111,5000,21,27,13495,0,1,1,0
1,3,122.0,alfa-romero,std,two,convertible,rwd,front,88.6,168.8,...,9.0,111,5000,21,27,16500,0,1,1,0
2,1,122.0,alfa-romero,std,two,hatchback,rwd,front,94.5,171.2,...,9.0,154,5000,19,26,16500,0,1,1,0
3,2,164,audi,std,four,sedan,fwd,front,99.8,176.6,...,10.0,102,5500,24,30,13950,0,1,1,0
4,2,164,audi,std,four,sedan,4wd,front,99.4,176.6,...,8.0,115,5500,18,22,17450,0,1,1,0

In [38]:
df.drop("aspiration", axis=1, inplace=True)
# change column names for clarity
df.rename(columns={'std':'aspiration-std', 'turbo': 'aspiration-turbo'}, inplace=True)
df.head()

,symboling,normalized-losses,make,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,fuel-type-diesel,fuel-type-gas,aspiration-std,aspiration-turbo
0,3,122.0,alfa-romero,two,convertible,rwd,front,88.6,168.8,64.1,...,9.0,111,5000,21,27,13495,0,1,1,0
1,3,122.0,alfa-romero,two,convertible,rwd,front,88.6,168.8,64.1,...,9.0,111,5000,21,27,16500,0,1,1,0
2,1,122.0,alfa-romero,two,hatchback,rwd,front,94.5,171.2,65.5,...,9.0,154,5000,19,26,16500,0,1,1,0
3,2,164,audi,four,sedan,fwd,front,99.8,176.6,66.2,...,10.0,102,5500,24,30,13950,0,1,1,0
4,2,164,audi,four,sedan,4wd,front,99.4,176.6,66.4,...,8.0,115,5500,18,22,17450,0,1,1,0

Save the new csv:

In [39]:
df.to_csv('cars_clean_df.csv', index=False)